version: '3.8'
services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - web

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./php:/var/www/html:ro
    depends_on:
      - php
    networks:
      - web

networks:
  web:
    driver: bridge
