version: '3.8'

services:
  php:
    image: php:8.2-fpm
    volumes:
      - ./php:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
